# 可以指定目錄
theme = "variant"
#baseURL = "/" 
baseURL = "http://u18docker/" 
languageCode = "en-us"
title = "隨手紀錄"
relativeurls = false
publishDir = "docs"
author = "lendjwjcen"

disableMermaid = false
disableLanguageSwitchingButton = true
enableGitInfo = false
linenos = "table"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$",
               "\\.dta$", ".log$","\\.accdb$","ori/.*","transfer/.*","\\.do$","\\.ado$"]
featherlight = false
#------------------------------------

uglyurls = true
enableEmoji = true    


[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5
# 和搜尋有關
[outputs]
 home = [ "HTML", "RSS", "JSON"]
 
[taxonomies]
  tag = "tags"
  category = "categories"
  series = "series"

[frontmatter]
  lastmod = [":git","lastmod", ":fileModTime", ":default"]

[markup]
#  defaultMarkdownHandler = "blackfriday"
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = false
    [markup.goldmark.parser]
      autoHeadingID = true
      autoHeadingIDType = "github"
      [markup.goldmark.parser.attribute]
        block = false
        title = true
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = false

   [markup.blackFriday]
    angledQuotes = false
    footnoteAnchorPrefix = ""
    footnoteReturnLinkContents = ""
    fractions = true
    hrefTargetBlank = false
    latexDashes = true
    nofollowLinks = false
    noreferrerLinks = false
    plainIDAnchors = true
    skipHTML = false
    smartDashes = true
    smartypants = true
    smartypantsQuotesNBSP = false
    taskLists = true
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineAnchors = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = false
    style = "monokai"
    tabWidth = 4    
  
[params]
  uglyurls = true
  email = "linchao@nkust.edu.tw"
  # extratheme
  nomath = false
  MathJaxURL = "//cdn.bootcss.com"
  
  #---------------------------------
  # Prefix URL to edit current page. Will display an "Edit this page" button on top right hand corner of every page.
  # Useful to give opportunity to people to create merge request for your doc.
  # See the config.toml file from this documentation site to have an example.
  #editsite = "http://u18docker.:3000/linchao/spida/_edit/master/content/"
  editsite = "http://alar:3000/linchao/spida/_edit/master/content/"
  # Description of the site, will be used in meta information
  description = "工作紀錄"
  # Shows a checkmark for visited pages on the menu
  showVisitedLinks = false
  # Disable search function. It will hide search bar
  disableSearch = false
  # Javascript and CSS cache are automatically busted when new version of site is generated.
  # Set this to true to disable this behavior (some proxies don't handle well this optimization)
  disableAssetsBusting = false
  # Set this to true to disable copy-to-clipboard button for inline code.
  disableInlineCopyToClipBoard = true
  # A title for shortcuts in menu is set by default. Set this to true to disable it.
  disableShortcutsTitle = false
  # If set to false, a Home button will appear below the search bar on the menu.
  # It is redirecting to the landing page of the current language if specified. (Default is "/")
  disableLandingPageButton = false
  # When using mulitlingual website, disable the switch language button.
  disableLanguageSwitchingButton = true
  # Hide breadcrumbs in the header and only show the current page title
  disableBreadcrumb = false
  # If set to true, prevents Hugo from including the mermaid module if not needed (will reduce load times and traffic)
  disableMermaid = true
  # Specifies the remote location of the mermaid js
  # customMermaidURL = "https://unpkg.com/mermaid@8.8.0/dist/mermaid.min.js"
  customMermaidURL = "https://cdnjs.cloudflare.com/ajax/libs/mermaid/8.11.0/mermaid.min.js"
  # Hide Next and Previous page buttons normally displayed full height beside content
  disableNextPrev = false
  # Order sections in menu by "weight" or "title". Default to "weight"
  ordersectionsby = "mix"
  # Change default color scheme with a variant one. Can be "red", "blue", "green".
  themeVariant = "mine"
  # Provide a list of custom css files to load relative from the `static/` folder in the site root.
  custom_css = ["css/demoContainer.css",
				"css/rmd.css"]
  # Change the title separator. Default to "::".
  titleSeparator = "-"	

# [[menu.shortcuts]]
# name = "<i class='fas fa-fw fa-paperclip'></i> 參考資料"
# url = "/reference.html"
# weight = 11  

# [[menu.shortcuts]]
# name = "<i class='fas fa-fw fa-paperclip'></i> 日誌"
# url = "/categories/tags/"
# weight = 11  


[security]
  enableInlineShortcodes = false

  [security.exec]
    allow = ['^dart-sass-embedded$', '^go$', '^npx$', '^postcss$']
    osEnv = ['(?i)^((HTTPS?|NO)_PROXY|PATH(EXT)?|APPDATA|TE?MP|TERM)$']

  [security.funcs]
    getenv = ['^HUGO_', '^WC_','^EDITURL']

  [security.http]
    methods = ['(?i)GET|POST']
    urls = ['.*']
