kind: pipeline
type: docker
name: default
trigger:
  branch:
    - master
 
steps:
- name: submodules
  image: alpine/git
  commands:
  - git submodule init
  - git submodule update --recursive --remote

- name: Build 
  image: airways1/hugo-builder
  pull: never
  volumes:
  - name: caddysite
    path: /drone/src/build
  commands:
  - hugo version
  - hugo --destination /drone/src/build
  #- minify -r -o /drone/src/build /drone/src/build

volumes:
- name: caddysite
  host:
    path: /home/linchao/raid/gitstack/caddysite
 